security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_login
                always_use_default_target_path: false
            logout:
                path: app_logout
                target: /mirano 

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/staff, roles: ROLE_STAFF }
